[2024-07-14T13:01:51.838+0100] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: pleaserun.get_sp500 scheduled__2024-07-14T11:50:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
