[2024-07-13T19:05:49.152+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T19:05:49.198+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hhh.get_sentiments manual__2024-07-13T17:59:49.364568+00:00 [queued]>
[2024-07-13T19:05:49.425+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hhh.get_sentiments manual__2024-07-13T17:59:49.364568+00:00 [queued]>
[2024-07-13T19:05:49.425+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-13T19:05:49.447+0100] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): get_sentiments> on 2024-07-13 17:59:49.364568+00:00
[2024-07-13T19:05:49.470+0100] {logging_mixin.py:188} WARNING - /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8327) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-13T19:05:49.471+0100] {standard_task_runner.py:63} INFO - Started process 8344 to run task
[2024-07-13T19:05:49.470+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'hhh', 'get_sentiments', 'manual__2024-07-13T17:59:49.364568+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dg1.py', '--cfg-path', '/var/folders/ml/zd6cs33j1gs1prd5lpns9pnc0000gn/T/tmps2i0yl1b']
[2024-07-13T19:05:49.472+0100] {standard_task_runner.py:91} INFO - Job 21: Subtask get_sentiments
[2024-07-13T19:05:49.563+0100] {task_command.py:426} INFO - Running <TaskInstance: hhh.get_sentiments manual__2024-07-13T17:59:49.364568+00:00 [running]> on host MAKs-MacBook-Pro.local
[2024-07-13T19:05:49.770+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='hhh' AIRFLOW_CTX_TASK_ID='get_sentiments' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T17:59:49.364568+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-13T17:59:49.364568+00:00'
[2024-07-13T19:05:49.772+0100] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T19:05:55.824+0100] {python.py:237} INFO - Done. Returned value was:            ds  negative  positive  ...   sadness  surprise    others
0  2024-07-13  0.004165  0.317974  ...  0.000974  0.002793  0.980527

[1 rows x 11 columns]
[2024-07-13T19:05:55.851+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T19:05:55.879+0100] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=hhh, task_id=get_sentiments, run_id=manual__2024-07-13T17:59:49.364568+00:00, execution_date=20240713T175949, start_date=20240713T180549, end_date=20240713T180555
[2024-07-13T19:05:55.989+0100] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-13T19:05:56.023+0100] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-13T19:05:56.025+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
